{
  "openapi": "3.0.0",
  "info": {
    "title": "Massive Open Online Course",
    "version": "1.0.0",
    "description": "API Docs For Massive Open Online Course"
  },
  "servers": [
    {
      "url": "http://localhost:5000",
      "description": "Development Server"
    }
  ],
  "components": {
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "AccessTokenIsRequired": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "enum": ["OK", "FAIL"],
            "example": "FAIL"
          },
          "message": {
            "type": "string",
            "example": "Invalid Token"
          },
          "data": {
            "example": null
          }
        }
      },
      "InvalidToken": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "enum": ["OK", "FAIL"],
            "example": "FAIL"
          },
          "message": {
            "type": "string",
            "example": "Access Token is Required"
          },
          "data": {
            "example": null
          }
        }
      },
      "Orders": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "enum": ["OK", "FAIL"],
            "example": "OK"
          },
          "message": {
            "type": "string",
            "example": null
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "string",
                  "format": "uuid",
                  "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                },
                "status": {
                  "type": "string",
                  "enum": ["APPROVED", "WAITING"],
                  "example": "WAITING"
                },
                "createdAt": {
                  "type": "string",
                  "format": "date-time",
                  "example": "2023-01-01T00:00:00.000Z"
                },
                "updatedAt": {
                  "type": "string",
                  "format": "date-time",
                  "example": "2023-01-01T00:00:00.000Z"
                },
                "userId": {
                  "type": "string",
                  "format": "uuid",
                  "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                },
                "courseId": {
                  "type": "string",
                  "format": "uuid",
                  "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                },
                "paymentId": {
                  "type": "string",
                  "format": "uuid",
                  "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                },
                "user": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "format": "uuid",
                      "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                    },
                    "name": {
                      "type": "string",
                      "example": "Windah Basudara"
                    },
                    "image": {
                      "type": "string",
                      "example": "image.png"
                    },
                    "phone": {
                      "type": "string",
                      "example": "08123456789"
                    },
                    "country": {
                      "type": "string",
                      "example": "Indonesia"
                    },
                    "city": {
                      "type": "string",
                      "example": "Bekasi"
                    },
                    "email": {
                      "type": "string",
                      "example": "example@gmail.com"
                    },
                    "password": {
                      "type": "string",
                      "example": "password123"
                    },
                    "role": {
                      "type": "string",
                      "enum": ["USER", "ADMIN"],
                      "example": "USER"
                    },
                    "createdAt": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2023-01-01T00:00:00.000Z"
                    },
                    "updatedAt": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2023-01-01T00:00:00.000Z"
                    }
                  }
                },
                "course": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "format": "uuid",
                      "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                    },
                    "title": {
                      "type": "string",
                      "example": "HTML"
                    },
                    "image": {
                      "type": "string",
                      "example": "image.png"
                    },
                    "subtitle": {
                      "type": "string",
                      "example": "English"
                    },
                    "description": {
                      "type": "string",
                      "example": "This is description"
                    },
                    "classCode": {
                      "type": "string",
                      "example": "XXX123"
                    },
                    "type": {
                      "type": "string",
                      "enum": ["FREE", "PREMIUM"],
                      "example": "PREMIUM"
                    },
                    "authorBy": {
                      "type": "string",
                      "example": "Windah Basudara"
                    },
                    "rating": {
                      "type": "number",
                      "example": 0
                    },
                    "price": {
                      "type": "number",
                      "example": 0
                    },
                    "level": {
                      "type": "string",
                      "enum": ["BEGINNER", "INTERMEDIATE", "ADVANCED"],
                      "example": "BEGINNER"
                    },
                    "createdAt": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2023-01-01T00:00:00.000Z"
                    },
                    "updatedAt": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2023-01-01T00:00:00.000Z"
                    },
                    "deletedAt": {
                      "type": "null",
                      "format": "date-time",
                      "example": "2023-01-01T00:00:00.000Z"
                    },
                    "createdBy": {
                      "type": "string",
                      "format": "uuid",
                      "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                    },
                    "updatedBy": {
                      "type": "string",
                      "format": "uuid",
                      "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                    },
                    "deletedBy": {
                      "type": "null",
                      "format": "uuid",
                      "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                    },
                    "categoryId": {
                      "type": "string",
                      "format": "uuid",
                      "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                    }
                  }
                },
                "payment": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "format": "uuid",
                      "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                    },
                    "cardNumber": {
                      "type": "string",
                      "example": "0123456789"
                    },
                    "cardName": {
                      "type": "string",
                      "example": "Windah Basudara"
                    },
                    "cvv": {
                      "type": "integer",
                      "example": 1234
                    },
                    "expiryDate": {
                      "type": "string",
                      "format": "date-time"
                    },
                    "amount": {
                      "type": "number",
                      "example": 0
                    },
                    "createdAt": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2023-01-01T00:00:00.000Z"
                    },
                    "updatedAt": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2023-01-01T00:00:00.000Z"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "Order": {
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "enum": ["OK", "FAIL"],
            "example": "OK"
          },
          "message": {
            "type": "string",
            "example": null
          },
          "data": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "format": "uuid",
                "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
              },
              "status": {
                "type": "string",
                "enum": ["APPROVED", "WAITING"],
                "example": "WAITING"
              },
              "createdAt": {
                "type": "string",
                "format": "date-time",
                "example": "2023-01-01T00:00:00.000Z"
              },
              "updatedAt": {
                "type": "string",
                "format": "date-time",
                "example": "2023-01-01T00:00:00.000Z"
              },
              "userId": {
                "type": "string",
                "format": "uuid",
                "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
              },
              "courseId": {
                "type": "string",
                "format": "uuid",
                "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
              },
              "paymentId": {
                "type": "string",
                "format": "uuid",
                "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
              },
              "user": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                  },
                  "name": {
                    "type": "string",
                    "example": "Windah Basudara"
                  },
                  "image": {
                    "type": "string",
                    "example": "image.png"
                  },
                  "phone": {
                    "type": "string",
                    "example": "08123456789"
                  },
                  "country": {
                    "type": "string",
                    "example": "Indonesia"
                  },
                  "city": {
                    "type": "string",
                    "example": "Bekasi"
                  },
                  "email": {
                    "type": "string",
                    "example": "example@gmail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "password123"
                  },
                  "role": {
                    "type": "string",
                    "enum": ["USER", "ADMIN"],
                    "example": "USER"
                  },
                  "createdAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00.000Z"
                  },
                  "updatedAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00.000Z"
                  }
                }
              },
              "course": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                  },
                  "title": {
                    "type": "string",
                    "example": "HTML"
                  },
                  "image": {
                    "type": "string",
                    "example": "image.png"
                  },
                  "subtitle": {
                    "type": "string",
                    "example": "English"
                  },
                  "description": {
                    "type": "string",
                    "example": "This is description"
                  },
                  "classCode": {
                    "type": "string",
                    "example": "XXX123"
                  },
                  "type": {
                    "type": "string",
                    "enum": ["FREE", "PREMIUM"],
                    "example": "PREMIUM"
                  },
                  "authorBy": {
                    "type": "string",
                    "example": "Windah Basudara"
                  },
                  "rating": {
                    "type": "number",
                    "example": 0
                  },
                  "price": {
                    "type": "number",
                    "example": 0
                  },
                  "level": {
                    "type": "string",
                    "enum": ["BEGINNER", "INTERMEDIATE", "ADVANCED"],
                    "example": "BEGINNER"
                  },
                  "createdAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00.000Z"
                  },
                  "updatedAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00.000Z"
                  },
                  "deletedAt": {
                    "type": "null",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00.000Z"
                  },
                  "createdBy": {
                    "type": "string",
                    "format": "uuid",
                    "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                  },
                  "updatedBy": {
                    "type": "string",
                    "format": "uuid",
                    "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                  },
                  "deletedBy": {
                    "type": "null",
                    "format": "uuid",
                    "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                  },
                  "categoryId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                  }
                }
              },
              "payment": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                  },
                  "cardNumber": {
                    "type": "string",
                    "example": "0123456789"
                  },
                  "cardName": {
                    "type": "string",
                    "example": "Windah Basudara"
                  },
                  "cvv": {
                    "type": "integer",
                    "example": 1234
                  },
                  "expiryDate": {
                    "type": "string",
                    "format": "date-time"
                  },
                  "amount": {
                    "type": "number",
                    "example": 0
                  },
                  "createdAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00.000Z"
                  },
                  "updatedAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00.000Z"
                  }
                }
              }
            }
          }
        }
      },
      "Course": {
        "type": "object",
        "properties": {
          "id": {
            "type": "uuid",
            "example": "550e8400-e29b-41d4-a716-446655440000"
          },
          "name": {
            "type": "string",
            "example": "Mobil Avanza"
          },
          "image": {
            "type": "string",
            "example": "https://firebasestorage.googleapis.com/v0/b/binar-course-402108.appspot.com/o/course-seed-1697616543758.jpg?alt=media&token=fbd8f719-7387-4415-b852-9da385cb99ad"
          },
          "rentPerDay": {
            "type": "integer",
            "example": 100000
          },
          "size": {
            "type": "string",
            "example": "Large"
          },
          "createdAt": {
            "type": "date-time",
            "example": "2023-10-20 20:30:13.053+07"
          },
          "updatedAt": {
            "type": "date-time",
            "example": "2023-10-20 20:30:13.053+07"
          },
          "deletedAt": {
            "type": "date-time",
            "example": "2023-10-20 20:30:13.053+07"
          },
          "createdBy": {
            "type": "uuid",
            "example": "550e8400-e29b-41d4-a716-446655440000"
          },
          "updatedBy": {
            "type": "uuid",
            "example": "550e8400-e29b-41d4-a716-446655440000"
          },
          "deletedBy": {
            "type": "uuid",
            "example": "550e8400-e29b-41d4-a716-446655440000"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Authentication",
      "description": "Endpoints for user authentication"
    },
    {
      "name": "Users",
      "description": "Endpoints for user management"
    },
    {
      "name": "Courses",
      "description": "Endpoints for course management"
    },
    {
      "name": "Modules",
      "description": "Endpoints for module management"
    },
    {
      "name": "Categories",
      "description": "Endpoints for category management"
    },
    {
      "name": "Orders",
      "description": "Endpoints for order management"
    },
    {
      "name": "CourseTrackings",
      "description": "Endpoints for course tracking management"
    },
    {
      "name": "ModuleTrackings",
      "description": "Endpoints for module tracking management"
    },
    {
      "name": "Notification",
      "description": "Endpoints for notification management"
    }
  ],
  "paths": {
    "/auth/register": {
      "post": {
        "tags": ["Authentication"],
        "summary": "User registration",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "default": "string",
                    "type": "string"
                  },
                  "email": {
                    "default": "string",
                    "type": "string"
                  },
                  "phone": {
                    "default": "string",
                    "type": "string"
                  },
                  "password": {
                    "default": "string",
                    "type": "string"
                  }
                },
                "required": ["name", "email", "phone", "password"]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "status": "OK",
                  "message": "Register Successfully",
                  "data": null
                }
              }
            }
          },
          "409": {
            "description": "",
            "content": {
              "application/json": {
                "examples": {
                  "Email Already Used": {
                    "value": {
                      "status": "FAIL",
                      "message": "Email Already Used",
                      "data": null
                    }
                  },
                  "Phone Already Used": {
                    "value": {
                      "status": "FAIL",
                      "message": "Phone Already Used",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Authentication"],
        "summary": "User login",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "emailOrPhone": {
                    "default": "string",
                    "type": "string"
                  },
                  "password": {
                    "default": "string",
                    "type": "string"
                  }
                },
                "required": ["emailOrPhone", "password"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "status": "OK",
                  "message": "Login Successfully",
                  "data": {
                    "accessToken": "JWT"
                  }
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "examples": {
                  "Email or Phone not Registered": {
                    "value": {
                      "status": "FAIL",
                      "message": "Email or Phone not Registered",
                      "data": null
                    }
                  },
                  "Wrong Password": {
                    "value": {
                      "status": "FAIL",
                      "message": "Wrong Password",
                      "data": null
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/auth/current-user": {
      "get": {
        "tags": ["Authentication"],
        "summary": "Get current user details",
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "status": "OK",
                  "message": null,
                  "data": {
                    "id": "string",
                    "name": "string",
                    "email": "string",
                    "image": "string",
                    "country": "string",
                    "city": "string",
                    "role": "string"
                  }
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccessTokenIsRequired"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/InvalidToken"
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "get": {
        "tags": ["Users"],
        "summary": "Get list of users",
        "responses": {
          "200": {
            "description": "List of users"
          }
        },
        "security": [
          {
            "BearerAuth": []
          }
        ]
      }
    },
    "/categories": {
      "get": {
        "tags": ["Categories"],
        "summary": "Get list of categories",
        "responses": {
          "200": {
            "description": "List of categories"
          }
        }
      }
    },
    "/orders": {
      "get": {
        "tags": ["Orders"],
        "summary": "Get list of orders",
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Orders"
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccessTokenIsRequired"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/InvalidToken"
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Orders"],
        "summary": "Create order",
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "userId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                  },
                  "courseId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                  },
                  "payment": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string",
                        "format": "uuid",
                        "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                      },
                      "cardNumber": {
                        "type": "string",
                        "example": "0123456789"
                      },
                      "cardName": {
                        "type": "string",
                        "example": "Windah Basudara"
                      },
                      "cvv": {
                        "type": "integer",
                        "example": 1234
                      },
                      "expiryDate": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "amount": {
                        "type": "number",
                        "example": 0
                      }
                    }
                  }
                },
                "required": ["userId", "courseId", "payment"]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "status": "OK",
                  "message": "Order Created Successfully",
                  "data": null
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccessTokenIsRequired"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/InvalidToken"
                }
              }
            }
          },
          "409": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAIL",
                  "message": "Order has already been placed",
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/orders/id": {
      "get": {
        "tags": ["Orders"],
        "summary": "Get order",
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "userId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                  }
                },
                "required": ["userId"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Order"
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccessTokenIsRequired"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/InvalidToken"
                }
              }
            }
          }
        }
      }
    },
    "/orders/approve": {
      "put": {
        "tags": ["Orders"],
        "summary": "Approve order",
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "orderId": {
                    "type": "string",
                    "format": "uuid",
                    "example": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
                  }
                },
                "required": ["orderId"]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "example": {
                  "status": "OK",
                  "message": "Order Approved Successfully",
                  "data": null
                }
              }
            }
          },
          "401": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AccessTokenIsRequired"
                }
              }
            }
          },
          "403": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/InvalidToken"
                }
              }
            }
          }
        }
      }
    },
    "/courses": {
            "get": {
                "tags": [
                    "Courses"
                ],
                "summary": "view course list data",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "responses": {
                    "200": {
                        "description": "View all course data successfully"
                    }
                }
                },
            "post": {
                "tags": [
                    "Courses"
                ],
                "summary": "create a new course ",
                "security": [
                    {
                        "BearerAuth": []
                    }      
                ],
                "requestBody": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "title": {
                                            "type": "string"
                                        },
                                        "subtitle": {
                                            "type": "number"
                                        },
                                        "description": {
                                            "type": "string"
                                        },
                                        "classCode": {
                                            "type": "string"
                                        },
                                        "type": {
                                            "type": "string"
                                        },
                                        "authorBy": {
                                            "type": "string"
                                        },
                                        "price": {
                                            "type": "number"
                                        },
                                        "level" : {
                                            "type": "string"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "responses": {
                        "201": {
                            "description": "create course data has been successfully"
                        },
                        "400": {
                            "description": "invalid data structure from client"
                        },
                        "401": {
                            "description": "unauthorized from user"
                        },
                        "403": {
                            "description": "forbidden from this resource"
                        },
                        "404": {
                            "description": "some error message"
                        }
                        
                    }
                },
            "put": {
                "tags": [
                    "Courses"
                ],
                "summary": "update course data",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "uuid"
                                    },
                                    "title": {
                                        "type": "string"
                                    },
                                    "subtitle": {
                                        "type": "number"
                                    },
                                    "description": {
                                        "type": "string"
                                    },
                                    "classCode": {
                                        "type": "string"
                                    },
                                    "type": {
                                        "type": "string"
                                    },
                                    "authorBy": {
                                        "type": "string"
                                    },
                                    "price": {
                                        "type": "number"
                                    },
                                    "level" : {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "update course data has been successfully"
                    },
                    "400": {
                        "description": "invalid data structure from client"
                    },
                    "401": {
                        "description": "unauthorized from user"
                    },
                    "403": {
                        "description": "forbidden from this resource"
                    },
                    "404": {
                        "description": "data not found"
                    }
                }
            },
            "delete": {
                "tags": [
                    "Courses"
                ],
                "summary": "delete data  course by id ",
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "requestBody": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "object",
                                    "properties": {
                                        "id": {
                                            "type": "uuid"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "responses": {
                        "201": {
                            "description": "deleted course data has been successfully"
                        },
                        "401": {
                            "description": "unauthorized from user"
                        },
                        "403": {
                            "description": "forbidden from this resource"
                        },
                        "404": {
                            "description": "some error message"
                        }
                        
                    }
                }
      },
    "/courses/search" : {
        "post": {
            "tags": [
                "Courses"
            ],
            "summary": "view data user by id ",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "uuid"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "View course data successfully"
                    },
                    "401": {
                        "description": "unauthorized from user"
                    },
                    "403": {
                        "description": "forbidden from this resource"
                    },
                    "404": {
                        "description": "some error message"
                    }
                    
                }
            }
    },
    "/courses/filter" : {
        "post": {
            "tags": [
                "Courses"
            ],
            "summary": "view data user by category id ",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "categoryId": {
                                        "type": "uuid"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "View course data successfully"
                    },
                    "401": {
                        "description": "unauthorized from user"
                    },
                    "403": {
                        "description": "forbidden from this resource"
                    },
                    "404": {
                        "description": "some error message"
                    }
                    
                }
            }
    },
    
    "/modules": {
        "get": {
            "tags": [
                "Modules"
            ],
            "summary": "view module list data",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "responses": {
                "200": {
                    "description": "View all module data successfully"
                }
            }
            },
        "post": {
            "tags": [
                "Modules"
            ],
            "summary": "create a new module ",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "title": {
                                        "type": "string"
                                    },
                                    "video": {
                                        "type": "string"
                                    },
                                    "time": {
                                        "type": "number"
                                    },
                                    "courseId": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "create module data has been successfully"
                    },
                    "400": {
                        "description": "invalid data structure from client"
                    },
                    "401": {
                        "description": "unauthorized from user"
                    },
                    "403": {
                        "description": "forbidden from this resource"
                    },
                    "404": {
                        "description": "some error message"
                    }
                    
                }
            },
        "put": {
            "tags": [
                "Modules"
            ],
            "summary": "update course data",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "uuid"
                                },
                                "title": {
                                    "type": "string"
                                },
                                "video": {
                                    "type": "string"
                                },
                                "time": {
                                    "type": "number"
                                },
                                "courseId": {
                                    "type": "uuid"
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "201": {
                    "description": "update module data has been successfully"
                },
                "400": {
                    "description": "invalid data structure from client"
                },
                "401": {
                    "description": "unauthorized from user"
                },
                "403": {
                    "description": "forbidden from this resource"
                },
                "404": {
                    "description": "data not found"
                }
            }
        }
    
    },
    "/modules/search" : {
        "post": {
            "tags": [
                "Modules"
            ],
            "summary": "view data modules by id ",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "uuid"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "View all module data successfully"
                    },
                    "401": {
                        "description": "unauthorized from user"
                    },
                    "403": {
                        "description": "forbidden from this resource"
                    },
                    "404": {
                        "description": "some error message"
                    }
                    
                }
            }
    },

    "/courseTrackings": {
        "get": {
            "tags": [
                "CourseTrackings"
            ],
            "summary": "view course tracking list data",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "responses": {
                "200": {
                    "description": "View all module data successfully"
                }
            }
            },
        "post": {
            "tags": [
                "CourseTrackings"
            ],
            "summary": "add new data course tracking  ",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "status": {
                                        "type": "string"
                                    },
                                    "userId": {
                                        "type": "uuid"
                                    },
                                    "courseId": {
                                        "type": "uuid"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "create module data has been successfully"
                    },
                    "400": {
                        "description": "invalid data structure from client"
                    },
                    "401": {
                        "description": "unauthorized from user"
                    },
                    "403": {
                        "description": "forbidden from this resource"
                    },
                    "404": {
                        "description": "some error message"
                    }
                    
                }
            },
        "put": {
            "tags": [
                "CourseTrackings"
            ],
            "summary": "update course tracking data",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "uuid"
                                },
                                "status": {
                                    "type": "string"
                                },
                                "userId": {
                                    "type": "uuid"
                                },
                                "courseId": {
                                    "type": "uuid"
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "201": {
                    "description": "update module data has been successfully"
                },
                "400": {
                    "description": "invalid data structure from client"
                },
                "401": {
                    "description": "unauthorized from user"
                },
                "403": {
                    "description": "forbidden from this resource"
                },
                "404": {
                    "description": "data not found"
                }
            }
        }
    },
    "/courseTrackings/search" : {
        "post": {
            "tags": [
                "CourseTrackings"
            ],
            "summary": "view course tracking data by id ",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "uuid"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "view course tracking by id"
                    },
                    "401": {
                        "description": "unauthorized from user"
                    },
                    "403": {
                        "description": "forbidden from this resource"
                    },
                    "404": {
                        "description": "some error message"
                    }
                    
                }
            }
    },

    "/moduleTrackings": {
        "get": {
            "tags": [
                "ModuleTrackings"
            ],
            "summary": "view course list data",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "responses": {
                "200": {
                    "description": "View all module tracking data successfully"
                }
            }
            },
        "post": {
            "tags": [
                "ModuleTrackings"
            ],
            "summary": "add new data course tracking  ",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "status": {
                                        "type": "string"
                                    },
                                    "userId": {
                                        "type": "uuid"
                                    },
                                    "courseId": {
                                        "type": "uuid"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "create module tracking data has been successfully"
                    },
                    "400": {
                        "description": "invalid data structure from client"
                    },
                    "401": {
                        "description": "unauthorized from user"
                    },
                    "403": {
                        "description": "forbidden from this resource"
                    },
                    "404": {
                        "description": "some error message"
                    }
                    
                }
            },
        "put": {
            "tags": [
                "ModuleTrackings"
            ],
            "summary": "update course tracking data",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "uuid"
                                },
                                "status": {
                                    "type": "string"
                                },
                                "userId": {
                                    "type": "uuid"
                                },
                                "courseId": {
                                    "type": "uuid"
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "201": {
                    "description": "update module tracking data has been successfully"
                },
                "400": {
                    "description": "invalid data structure from client"
                },
                "401": {
                    "description": "unauthorized from user"
                },
                "403": {
                    "description": "forbidden from this resource"
                },
                "404": {
                    "description": "data not found"
                }
            }
        }
    },

    "/moduleTrackings/search" : {
        "post": {
            "tags": [
                "ModuleTrackings"
            ],
            "summary": "view course tracking data by id ",
            "security": [
                {
                    "BearerAuth": []
                }
            ],
            "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "uuid"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "View all module tracking data successfully"
                    },
                    "401": {
                        "description": "unauthorized from user"
                    },
                    "403": {
                        "description": "forbidden from this resource"
                    },
                    "404": {
                        "description": "some error message"
                    }
                    
                }
            }
    }
  }
}
